# Generated by Django 4.1.3 on 2022-12-10 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('annuaire', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='entreprise',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='contact',
            name='prenom',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
